name: 'Update matter_sdk submodule'
description: 'Composite action to update the matter_sdk submodule and create a PR.'
inputs:
  target_branch:
    description: 'Target branch to update the submodule on'
    required: true
  app-id:
    description: 'GitHub App ID'
    required: false
  private-key:
    description: 'GitHub App private key'
    required: false
outputs:
  pr_branch:
    description: 'The name of the created PR branch (if any)'
    value: ${{ steps.update_submodule.outputs.pr_branch }}
runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App token
      id: generate_token
      if: inputs.app-id != '' && inputs.private-key != ''
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.target_branch }}
        token: ${{ steps.generate_token.outputs.token || github.token }}
        submodules: false

    - name: Update submodule
      id: update_submodule
      shell: bash
      run: |
        git submodule update --init third_party/matter_sdk
        short_hash_before=$(cd third_party/matter_sdk && git rev-parse --short HEAD)
        echo "short_hash_before=${short_hash_before}" >> $GITHUB_OUTPUT
        cd third_party/matter_sdk
        git fetch origin ${{ inputs.target_branch }}
        git checkout origin/${{ inputs.target_branch }}
        cd ../..
        git add third_party/matter_sdk
        if git diff-index --quiet HEAD; then
          echo "empty=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        short_hash=$(cd third_party/matter_sdk && git rev-parse --short HEAD)
        echo "short_hash=${short_hash}" >> $GITHUB_OUTPUT
        echo "pr_branch=update-matter-sdk-${{ inputs.target_branch }}" >> $GITHUB_OUTPUT

    - name: Create PR
      if: steps.update_submodule.outputs.empty != 'true'
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ steps.generate_token.outputs.token || github.token }}
        base: ${{ inputs.target_branch }}
        commit-message: "Update matter_sdk submodule to ${{ steps.update_submodule.outputs.short_hash }}"
        title: "[${{ inputs.target_branch }}] Update matter_sdk submodule to ${{ steps.update_submodule.outputs.short_hash }}"
        body: |
          Bumps matter_sdk submodule from `${{ steps.update_submodule.outputs.short_hash_before }}` to `${{ steps.update_submodule.outputs.short_hash }}`.

          See diff at https://github.com/SiliconLabsSoftware/matter_sdk/compare/${{ steps.update_submodule.outputs.short_hash_before }}...${{ steps.update_submodule.outputs.short_hash }}
        branch: ${{ steps.update_submodule.outputs.pr_branch }}